remote_theme: coursweb/jk-theme

title: Hélène CHANAL

description: Description de cet exemple

lang: fr-FR

robots: noindex, nofollow

# menu 
chapters:
 - title: CV
   url: https://CV.ch/
 - title: project
   url: https://project.ch/
 - title: publications
   url: https://publications.ch/

# pied de page   
footer_col_1: <ul class="contact-list">
  <li>Institut Pascal / Clermont Auvergne INP, Aubière</li> <li>2026</li></ul>

